/**
 * EsPReSSO - Extension for Processing and Recognition of Single Sign-On Protocols.
 * Copyright (C) 2015/ Tim Guenther and Christian Mainka
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */
package de.rub.nds.burp.espresso.gui;

/**
 *
 * @author Tim Guenther
 */
public class UIHelp extends javax.swing.JPanel {

    /**
     * Creates new form UIHelp
     */
    public UIHelp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headline = new javax.swing.JLabel();
        subheadline = new javax.swing.JLabel();
        helpContainerPanel = new javax.swing.JTabbedPane();
        apiPanel = new javax.swing.JPanel();
        protocolsTabbedPane = new javax.swing.JTabbedPane();
        samlPane = new javax.swing.JTabbedPane();
        smal1Pane = new javax.swing.JPanel();
        saml2Pane = new javax.swing.JPanel();
        openidPane = new javax.swing.JTabbedPane();
        openid11Pane = new javax.swing.JPanel();
        openid2Pane = new javax.swing.JPanel();
        openidconnectPane = new javax.swing.JPanel();
        oauthPane = new javax.swing.JTabbedPane();
        oauth1Pane = new javax.swing.JPanel();
        oauth2Pane = new javax.swing.JPanel();
        browseridPane = new javax.swing.JTabbedPane();
        flowchartPane = new javax.swing.JPanel();

        headline.setText("Help for Using this Extension at: https://github.com/some_uri");

        subheadline.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        subheadline.setText("API and Scripting Help...");

        javax.swing.GroupLayout apiPanelLayout = new javax.swing.GroupLayout(apiPanel);
        apiPanel.setLayout(apiPanelLayout);
        apiPanelLayout.setHorizontalGroup(
            apiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        apiPanelLayout.setVerticalGroup(
            apiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );

        helpContainerPanel.addTab("API", apiPanel);

        smal1Pane.setEnabled(false);
        smal1Pane.setFocusable(false);

        javax.swing.GroupLayout smal1PaneLayout = new javax.swing.GroupLayout(smal1Pane);
        smal1Pane.setLayout(smal1PaneLayout);
        smal1PaneLayout.setHorizontalGroup(
            smal1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        smal1PaneLayout.setVerticalGroup(
            smal1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        samlPane.addTab("SAML 1.0", smal1Pane);

        javax.swing.GroupLayout saml2PaneLayout = new javax.swing.GroupLayout(saml2Pane);
        saml2Pane.setLayout(saml2PaneLayout);
        saml2PaneLayout.setHorizontalGroup(
            saml2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        saml2PaneLayout.setVerticalGroup(
            saml2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        samlPane.addTab("SAML 2.0", saml2Pane);

        protocolsTabbedPane.addTab("SAML", samlPane);

        javax.swing.GroupLayout openid11PaneLayout = new javax.swing.GroupLayout(openid11Pane);
        openid11Pane.setLayout(openid11PaneLayout);
        openid11PaneLayout.setHorizontalGroup(
            openid11PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        openid11PaneLayout.setVerticalGroup(
            openid11PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        openidPane.addTab("OpenID 1.1", openid11Pane);

        javax.swing.GroupLayout openid2PaneLayout = new javax.swing.GroupLayout(openid2Pane);
        openid2Pane.setLayout(openid2PaneLayout);
        openid2PaneLayout.setHorizontalGroup(
            openid2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        openid2PaneLayout.setVerticalGroup(
            openid2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        openidPane.addTab("OpenID 2.0", openid2Pane);

        javax.swing.GroupLayout openidconnectPaneLayout = new javax.swing.GroupLayout(openidconnectPane);
        openidconnectPane.setLayout(openidconnectPaneLayout);
        openidconnectPaneLayout.setHorizontalGroup(
            openidconnectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        openidconnectPaneLayout.setVerticalGroup(
            openidconnectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        openidPane.addTab("OpenID Connect", openidconnectPane);

        protocolsTabbedPane.addTab("OpenID", openidPane);

        javax.swing.GroupLayout oauth1PaneLayout = new javax.swing.GroupLayout(oauth1Pane);
        oauth1Pane.setLayout(oauth1PaneLayout);
        oauth1PaneLayout.setHorizontalGroup(
            oauth1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        oauth1PaneLayout.setVerticalGroup(
            oauth1PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        oauthPane.addTab("OAuth 1.0", oauth1Pane);

        javax.swing.GroupLayout oauth2PaneLayout = new javax.swing.GroupLayout(oauth2Pane);
        oauth2Pane.setLayout(oauth2PaneLayout);
        oauth2PaneLayout.setHorizontalGroup(
            oauth2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        oauth2PaneLayout.setVerticalGroup(
            oauth2PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        oauthPane.addTab("OAuth 2.0", oauth2Pane);

        protocolsTabbedPane.addTab("OAuth", oauthPane);

        browseridPane.setDoubleBuffered(true);
        browseridPane.setFocusable(false);

        javax.swing.GroupLayout flowchartPaneLayout = new javax.swing.GroupLayout(flowchartPane);
        flowchartPane.setLayout(flowchartPaneLayout);
        flowchartPaneLayout.setHorizontalGroup(
            flowchartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        flowchartPaneLayout.setVerticalGroup(
            flowchartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        browseridPane.addTab("Flowchart", flowchartPane);

        protocolsTabbedPane.addTab("BrowserID", browseridPane);

        helpContainerPanel.addTab("Protocols", protocolsTabbedPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headline)
                            .addComponent(subheadline))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(helpContainerPanel))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(headline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subheadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpContainerPanel)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel apiPanel;
    private javax.swing.JTabbedPane browseridPane;
    private javax.swing.JPanel flowchartPane;
    private javax.swing.JLabel headline;
    private javax.swing.JTabbedPane helpContainerPanel;
    private javax.swing.JPanel oauth1Pane;
    private javax.swing.JPanel oauth2Pane;
    private javax.swing.JTabbedPane oauthPane;
    private javax.swing.JPanel openid11Pane;
    private javax.swing.JPanel openid2Pane;
    private javax.swing.JTabbedPane openidPane;
    private javax.swing.JPanel openidconnectPane;
    private javax.swing.JTabbedPane protocolsTabbedPane;
    private javax.swing.JPanel saml2Pane;
    private javax.swing.JTabbedPane samlPane;
    private javax.swing.JPanel smal1Pane;
    private javax.swing.JLabel subheadline;
    // End of variables declaration//GEN-END:variables
}
