/**
 * EsPReSSO - Extension for Processing and Recognition of Single Sign-On Protocols.
 * Copyright (C) 2015 Tim Guenther and Christian Mainka
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */
package de.rub.nds.burp.espresso.editor.saml;

import burp.IBurpExtenderCallbacks;
import burp.IExtensionHelpers;
import de.rub.nds.burp.utilities.Logging;
import de.rub.nds.burp.utilities.XMLHelper;
import de.rub.nds.burp.utilities.listeners.AbstractCodeEvent;
import de.rub.nds.burp.utilities.listeners.CodeListenerController;
import de.rub.nds.burp.utilities.listeners.ICodeListener;
import java.awt.Font;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.ByteArrayInputStream;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.text.DefaultCaret;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import wsattacker.library.xmlutilities.dom.DomUtilities;

/**
 * Certificate Viewer
 * @author Nurullah Erinola
 */
public class UICertificateViewer extends javax.swing.JPanel implements ICodeListener {

    private final IBurpExtenderCallbacks callbacks;
    private final IExtensionHelpers helpers;
    
    private CodeListenerController listeners = null;
    private JLabel jLabelNoCert;
    private boolean wrapLines;
    private String code;
    private ArrayList<X509Certificate> certificates;
    private ArrayList<String> certificatesBase64;
    private DefaultListModel certificatePaths;    
    
    /**
     * Creates new form UICertificateViewer
     * @param callbacks
     */
    public UICertificateViewer(IBurpExtenderCallbacks callbacks) {
        this.callbacks = callbacks;
        this.helpers = callbacks.getHelpers();
        wrapLines = Boolean.valueOf(callbacks.loadExtensionSetting("wrapLinesInCertificateViewer"));
        jLabelNoCert = new JLabel("No certificates recognized.");
        jLabelNoCert.setFont(new Font("Dialog", 1, 15));
        this.add(jLabelNoCert); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCertificateNames = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextareaOrgCert = new javax.swing.JTextArea();
        jButtonCopy = new javax.swing.JButton();
        jCheckBoxSoftwraps = new javax.swing.JCheckBox();

        jLabel1.setText("Select certificate:");

        jListCertificateNames.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jListCertificateNames.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCertificateNamesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListCertificateNames);

        jLabel2.setText("Selected certificate:");

        jTextareaOrgCert.setEditable(false);
        jTextareaOrgCert.setColumns(20);
        jTextareaOrgCert.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextareaOrgCert.setRows(5);
        jScrollPane2.setViewportView(jTextareaOrgCert);

        jButtonCopy.setText("Copy as PEM");
        jButtonCopy.setToolTipText("Copy certificate as PEM to clipboard.");
        jButtonCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopyActionPerformed(evt);
            }
        });

        jCheckBoxSoftwraps.setText("Softwraps for long lines");
        jCheckBoxSoftwraps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSoftwrapsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCopy))
                            .addComponent(jCheckBoxSoftwraps))
                        .addGap(0, 299, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonCopy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSoftwraps)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListCertificateNamesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCertificateNamesValueChanged
        X509Certificate cert = certificates.get(jListCertificateNames.getSelectedIndex());
        jTextareaOrgCert.setText(cert.toString());
        jTextareaOrgCert.setCaretPosition(0);
    }//GEN-LAST:event_jListCertificateNamesValueChanged

    private void jButtonCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopyActionPerformed
        String toCopy = "-----BEGIN CERTIFICATE-----\n"
                + certificatesBase64.get(jListCertificateNames.getSelectedIndex()) 
                + "\n-----END CERTIFICATE-----";
        StringSelection stringSelection = new StringSelection(toCopy);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_jButtonCopyActionPerformed

    private void jCheckBoxSoftwrapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSoftwrapsActionPerformed
        if(jCheckBoxSoftwraps.isSelected()) {
            wrapLines = true;
            jTextareaOrgCert.setLineWrap(true);
            callbacks.saveExtensionSetting("wrapLinesInCertificateViewer", "true");
        } else {
            wrapLines = false;
            jTextareaOrgCert.setLineWrap(false); 
            callbacks.saveExtensionSetting("wrapLinesInCertificateViewer", "false");
        }
    }//GEN-LAST:event_jCheckBoxSoftwrapsActionPerformed

    /**
     * Return true if message contains certificates
     */
    public boolean containsCertificate() {
        Document doc = XMLHelper.stringToDom(code);
        if(doc != null) {
            return doc.getElementsByTagNameNS("*", "X509Certificate").getLength() != 0;
        } else {
            return false;
        }
    }

    /**
     * Update JList with certifcate paths
     */
    private void update() {
        certificates = new ArrayList<>();
        certificatesBase64 = new ArrayList<>();
        certificatePaths = new DefaultListModel();
        NodeList list = XMLHelper.stringToDom(code).getElementsByTagNameNS("*", "X509Certificate");
        for(int i = 0; i < list.getLength(); i++) {
            try {
                // Save certificate as Base64 encoded
                certificatesBase64.add(list.item(0).getTextContent());
                // Save certificate as X509Certificate object
                CertificateFactory cf = CertificateFactory.getInstance("X.509");
                X509Certificate certificate = (X509Certificate) cf.generateCertificate(
                        new ByteArrayInputStream(helpers.base64Decode(list.item(i).getTextContent())));
                certificates.add(certificate);
                // Save path of certficate
                certificatePaths.addElement(DomUtilities.getFastXPath(list.item(i)));
            } catch (CertificateException ex) {
                Logging.getInstance().log(getClass(), ex);
            }
        }
        jListCertificateNames.setModel(certificatePaths);
        jListCertificateNames.setSelectedIndex(0);
    }
    
    /**
     * Is called every time new Code is available.
     * @param evt {@link de.rub.nds.burp.utilities.listeners.AbstractCodeEvent} The new source code.
     */
    @Override
    public void setCode(AbstractCodeEvent evt) {
        code = evt.getCode();
        if(containsCertificate()) {
            this.removeAll();
            initComponents();
            jTextareaOrgCert.setLineWrap(wrapLines);
            jCheckBoxSoftwraps.setSelected(wrapLines);
            update();
        } else {
            this.removeAll();
            this.add(jLabelNoCert);
        }
    }

    /**
     * Set the listener for the editor.
     * @param listeners {@link de.rub.nds.burp.utilities.listeners.CodeListenerController}
     */
    @Override
    public void setListener(CodeListenerController listeners) {
        this.listeners = listeners;
        this.listeners.addCodeListener(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCopy;
    private javax.swing.JCheckBox jCheckBoxSoftwraps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListCertificateNames;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextareaOrgCert;
    // End of variables declaration//GEN-END:variables
}
