/**
 * EsPReSSO - Extension for Processing and Recognition of Single Sign-On Protocols.
 * Copyright (C) 2015 Tim Guenther and Christian Mainka
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */
package de.rub.nds.burp.espresso.gui.attacker.saml.xsw;

import de.rub.nds.burp.utilities.Logging;
import de.rub.nds.burp.utilities.XMLHelper;
import de.rub.nds.burp.utilities.listeners.AbstractCodeEvent;
import de.rub.nds.burp.utilities.listeners.CodeListenerController;
import de.rub.nds.burp.utilities.listeners.ICodeListener;
import de.rub.nds.burp.utilities.table.xsw.TableEntry;
import de.rub.nds.burp.utilities.table.xsw.TableModel;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Function;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableRowSorter;
import javax.xml.xpath.XPathExpressionException;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import wsattacker.library.schemaanalyzer.SchemaAnalyzer;
import wsattacker.library.schemaanalyzer.SchemaAnalyzerFactory;
import wsattacker.library.signatureWrapping.option.Payload;
import wsattacker.library.signatureWrapping.util.signature.SignatureManager;
import wsattacker.library.signatureWrapping.xpath.wrapping.WrappingOracle;
import wsattacker.library.xmlutilities.dom.DomUtilities;

/**
 * The Signature Wrapping Attack
 * @author Nurullah Erinola
 * @version 1.0
 */
public class UISigWrapAttackInit extends javax.swing.JPanel implements ICodeListener {

    private static final SchemaAnalyzer samlSchemaAnalyser = SchemaAnalyzerFactory.getInstance(SchemaAnalyzerFactory.SAML);
    private WrappingOracle wrappingOracle;
    
    private Document doc = null;
    private Document newDoc = null;
    private CodeListenerController listeners = null;
    private HashMap<String, String> valuePairs;
    private TableModel tableModel;
    private JTable table;
    private boolean firstTime = true;
    private int max = -1;
    private ArrayList<Payload> payloadList;
    private UISigWrapExec uiExec;
    private Consumer<Integer> switchTabFunc;
    private final Integer EXEC_ATTACK_TAB_INDEX = 1;
    
    /**
     * Creates new form UISigWrapAttack
     */
    public UISigWrapAttackInit(UISigWrapExec uiExec) {
        initComponents();
        jLabelNode.setText("");
        valuePairs = new HashMap<>();
        initTable();
        this.uiExec = uiExec;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonReload = new javax.swing.JButton();
        jButtonGenerateVectors = new javax.swing.JButton();
        jCheckBoxWrapLines = new javax.swing.JCheckBox();
        jLabelVectors = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNewValue = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        rTextScrollPane = new org.fife.ui.rtextarea.RTextScrollPane();
        rSyntaxTextArea = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
        jTextFieldCurrentValue = new javax.swing.JTextField();
        jLabelNode = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Message:");

        jButtonReload.setText("Reload");
        jButtonReload.setToolTipText("Load latest message.");
        jButtonReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReloadActionPerformed(evt);
            }
        });

        jButtonGenerateVectors.setText("Generate vectors");
        jButtonGenerateVectors.setEnabled(false);
        jButtonGenerateVectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateVectorsActionPerformed(evt);
            }
        });

        jCheckBoxWrapLines.setText("Softwraps for long lines");
        jCheckBoxWrapLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWrapLinesActionPerformed(evt);
            }
        });

        jLabelVectors.setForeground(new java.awt.Color(255, 0, 0));
        jLabelVectors.setText("Minimum one textnode pair necessary!");

        jLabel3.setText("Current value:");

        jLabel4.setText("New value:");

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel5.setText("Textnodes to be replaced automatically:");

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        rTextScrollPane.setAutoscrolls(true);
        rTextScrollPane.setLineNumbersEnabled(true);

        rSyntaxTextArea.setEditable(false);
        rSyntaxTextArea.setCodeFoldingEnabled(true);
        rSyntaxTextArea.setSyntaxEditingStyle("text/xml");
        rTextScrollPane.setViewportView(rSyntaxTextArea);

        jLabelNode.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNode.setText("Error");

        jLabel7.setText("Overview:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rTextScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneTable)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCurrentValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNewValue))
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxWrapLines)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonReload))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNode))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonGenerateVectors)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVectors)))
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBoxWrapLines)
                    .addComponent(jButtonReload))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rTextScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelNode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldCurrentValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNewValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButtonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerateVectors)
                    .addComponent(jLabelVectors))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() {
        tableModel = new TableModel();
        table = new JTable(tableModel);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneTable.setViewportView(table);
        //Enable sorting
        TableRowSorter<TableModel> sorter = new TableRowSorter<>();
        table.setRowSorter(sorter);
        sorter.setModel(tableModel);
        // Set event listener
        tableModel.addTableModelListener(new TableModelListener() {
                @Override
                public void tableChanged(TableModelEvent e) {
                    if (e.getType() == TableModelEvent.INSERT || e.getType() == TableModelEvent.DELETE) {
                        if(tableModel.getRowCount() > 0) {
                            jButtonGenerateVectors.setEnabled(true);
                            jLabelVectors.setText("Press button to generate vectors.");
                        } else {
                            jButtonGenerateVectors.setEnabled(false);
                            jLabelVectors.setText("Minimum one textnode pair necessary!");
                        }
                        uiExec.enableObjects(false);
                    }
                }
        });
    }
    
    private void jButtonReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReloadActionPerformed
        doc = newDoc;
        // Init manager and set message
        initSigManager();
        // Clean up
        jTextFieldCurrentValue.setText("");
        jTextFieldNewValue.setText("");
        jLabelNode.setText("");
        jLabelVectors.setText("Minimum one textnode pair necessary!");
        valuePairs.clear();
        tableModel.clearAll();
        jButtonGenerateVectors.setEnabled(false);
        // Update tab
        uiExec.enableObjects(false);
    }//GEN-LAST:event_jButtonReloadActionPerformed

    private void jButtonGenerateVectorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateVectorsActionPerformed
        if (payloadList.isEmpty()) {
            jLabelVectors.setText("No signatures available!");
            return;
        }
        // Repalce values
        for (int i = 0; i < payloadList.size(); i++) {
            Document payload = XMLHelper.stringToDom(payloadList.get(i).getValue());
            for (Map.Entry pair : valuePairs.entrySet()) {
                try {
                    Node node = DomUtilities.evaluateXPath(payload, pair.getKey().toString()).get(0);
                    node.setTextContent(pair.getValue().toString());
                } catch (XPathExpressionException ex) {
                    Logging.getInstance().log(getClass(), "Could not replace value.", Logging.ERROR);
                }
            }
            payloadList.get(i).setPayloadElement(payload.getDocumentElement());
        }
        // Init oracle
        wrappingOracle = new WrappingOracle(doc, payloadList, samlSchemaAnalyser);
        max = wrappingOracle.maxPossibilities();
        jLabelVectors.setText(max + " possible vectors!");
        // Update tab
        uiExec.initOracle(wrappingOracle);
        uiExec.enableObjects(max > 0);
        switchTabFunc.accept(EXEC_ATTACK_TAB_INDEX);
    }//GEN-LAST:event_jButtonGenerateVectorsActionPerformed

    private void jCheckBoxWrapLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWrapLinesActionPerformed
        if (jCheckBoxWrapLines.isSelected()) {
            rSyntaxTextArea.setLineWrap(true);
        } else {
            rSyntaxTextArea.setLineWrap(false);
        }
    }//GEN-LAST:event_jCheckBoxWrapLinesActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        ArrayList<String> xPaths = new ArrayList<>();
        // Search only in signed elements
        for (int i = 0; i < payloadList.size(); i++) {
            Document payload = DomUtilities.createNewDomFromNode(payloadList.get(i).getSignedElement());
            xPaths.addAll(XMLHelper.findNodeByValue(payload, jTextFieldCurrentValue.getText()));
        }
        if(xPaths.isEmpty()) {
            jLabelNode.setText("No node found with provided value!");
            return;
        }
        for (int i = 0; i < xPaths.size(); i++) {
            String selection = xPaths.get(i);
            // Add pair
            if (!selection.equals("")  && !valuePairs.containsKey(selection)) {
                jLabelNode.setText("");
                valuePairs.put(selection, jTextFieldNewValue.getText());
                tableModel.addRow(new TableEntry(selection, jTextFieldCurrentValue.getText(), jTextFieldNewValue.getText()));
            } else {
                jLabelNode.setText("New value for '" + jTextFieldCurrentValue.getText() + "' already added. Delete existing entry to replace it!");
            } 
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if (table.getSelectedRow() != -1) {
            valuePairs.remove((String) tableModel.getValueAt(table.getSelectedRow(), 0));
            tableModel.remove(table.getSelectedRow());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed
    
    private void initSigManager() {
        SignatureManager sigManager = new SignatureManager();
        sigManager.setDocument(doc);
        payloadList = (ArrayList<Payload>) sigManager.getPayloads();
        // Set message
        if (payloadList.isEmpty()) {
            rSyntaxTextArea.setText("<Error>No signatures available. Attack can't be executed!</Error>");
        } else if (payloadList.size() != 1) {
            rSyntaxTextArea.setText("<Error>Attacker works only for messages with one signature!</Error>");
        } else {
            rSyntaxTextArea.setText(XMLHelper.docToString(doc));
        }
        rSyntaxTextArea.setCaretPosition(0);
    }
    
    /**
     * Is called every time new Code is available.
     * @param evt {@link de.rub.nds.burp.utilities.listeners.AbstractCodeEvent} The new source code.
     */
    @Override
    public void setCode(AbstractCodeEvent evt) {
        if (firstTime) {
            this.doc = XMLHelper.stringToDom(new String(evt.getCode()));
            this.newDoc = XMLHelper.stringToDom(new String(evt.getCode()));         
            // Init manager and set message
            initSigManager();
            rTextScrollPane.setLineNumbersEnabled(true);
            firstTime = false;
            
        } else {
            this.newDoc = XMLHelper.stringToDom(new String(evt.getCode()));    
        }
    }
    
    /**
     * Set the listener for the editor.
     * @param listeners {@link de.rub.nds.burp.utilities.listeners.CodeListenerController}
     */
    @Override
    public void setListener(CodeListenerController listeners) {
        this.listeners = listeners;
        this.listeners.addCodeListener(this);
    }

    public void setSwitchTabFunc(Consumer<Integer> selectTab) {
        this.switchTabFunc = selectTab;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonGenerateVectors;
    private javax.swing.JButton jButtonReload;
    private javax.swing.JCheckBox jCheckBoxWrapLines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNode;
    private javax.swing.JLabel jLabelVectors;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextFieldCurrentValue;
    private javax.swing.JTextField jTextFieldNewValue;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea rSyntaxTextArea;
    private org.fife.ui.rtextarea.RTextScrollPane rTextScrollPane;
    // End of variables declaration//GEN-END:variables
}
